language: objective-c
xcode_project: iPhoneCalculator.xcodeproj 
before_install: 
        - brew install imagemagick 
        - ./install_fonts.sh
        - bundle install
before_script: "./build.sh"
script: "ruby cucumber-runner.rb"
