language: objective-c
xcode_project: iPhoneCalculator.xcodeproj
install:
- brew install imagemagick
- ./install_fonts.sh
- bundle install
before_script: ./build.sh
script: ruby cucumber-runner.rb
deploy:
  provider: s3
  access_key_id: AKIAI77N7VGZLSFJ7ZIQ
  secret_access_key:
    secure: QNyjxZQcpYIcpwZ7fMvqPhHg05BwnRlcsqSAWkHh7Cj2WLtpFbcTJ4u/yVGQtS1iSzz5p1FpDlc97iJgU88rf/Hk/U+/vBzIlZV5Bj3t88dMJSegds8UdZ8Ij1hvBjL7hTIc7+3oIsT9copk1ix44/H3X1yuVYG9FWyxbLoJaRI=
  bucket: rickys-builds
  skip_cleanup: true
  upload-dir: travis-builds
  acl: private
  on:
    repo: codingricky/iPhoneCalculator
