language: objective-c
xcode_project: iPhoneCalculator.xcodeproj
install:
  - brew install imagemagick
  - ./install_fonts.sh
  - bundle install
before_script: ./build.sh
script: ruby cucumber-runner.rb
deploy:
  provider: s3
  access_key_id: AKIAI77N7VGZLSFJ7ZIQ
  secret_access_key:
    secure: V7ohTJAKMFSPFDqxVEguxxN876b6jtsGgN3vqQ1QZmJVn3dp0k7M0sX+7ROabQzU5ke+1s2yLKmLR2C0DjlV3nE2TvDFvChEvQURnQ/6ezyhrwpRzTPquosrBfU/26l/PvQkAqGjbotAStgm17Z2+z983wGvUJkH/zytX5h25hU=
  bucket: rickys-builds
  local-dir: screenshots
  upload-dir: travis-builds
  acl: !ruby/string:HighLine::String |-
    cHJpdmF0ZQ==
  on:
    repo: codingricky/iPhoneCalculator
