language: objective-c
xcode_project: iPhoneCalculator.xcodeproj
install:
- brew install imagemagick
- ./install_fonts.sh
- bundle install
before_script: ./build.sh
script: ruby cucumber-runner.rb
deploy:
  provider: s3
  access_key_id: AKIAI77N7VGZLSFJ7ZIQ
  secret_access_key:
    secure: SQwXHE8FDcC0eqbgRAmtsSlgUcVHrDYrppuIRbRYR02RZR1SR71T0h1vEQeo9i2GG6wpsdoWqgqfCyVyYWXoAy6L81g3HK1Odnte8aULjgJwkUtkgBufKcq8KQDVZ6k4oYVNOSj+h/S96Y3N+CY+auWtRgkDj4+oTuupdc4hhZk=
  bucket: rickys-builds
  upload-dir: travis-builds
  acl: public_read
  on:
    repo: codingricky/iPhoneCalculator
addons:
  artifacts:
    paths:
    - $(git ls-files -o | tr "\n" ":")
    - $HOME/screenshots/screenshot.png